from.import html as html,json as json,morse as morse,msy as msy,standard_galactic_alphabet as standard_galactic_alphabet
__all__=['base_x_decode_from_binary','base_x_encode_to_binary','encode','decode','msy','morse','html','standard_galactic_alphabet','json']
def base_x_decode_from_binary(binary_data:bytes,base:int)->str:...
def base_x_encode_to_binary(data_in_base_x:str,base:int)->bytes:...
def encode(x:str)->str:...
def decode(data:str)->str:...