from typing import Any

__all__ = ['json5_to_json', 'json_to_json5', 'hjson_to_json', 'json_to_hjson', 'hjson_to_json5', 'json5_to_hjson', 'loose_decode_json', 'is_valid_json']

def json5_to_json(string: str) -> str: ...
def json_to_json5(string: str) -> str: ...
def hjson_to_json(string: str) -> str: ...
def json_to_hjson(string: str) -> str: ...
def hjson_to_json5(string: str) -> str: ...
def json5_to_hjson(string: str) -> str: ...
def loose_decode_json(json_str: str) -> dict[str, Any]: ...
def is_valid_json(json_str: str) -> bool: ...
