__all__ = ['is_valid_function_name', 'is_valid_registry_name', 'is_number_range', 'is_valid_scoreboard_name']

def is_valid_function_name(name: str) -> bool: ...
def is_valid_registry_name(input_str: str) -> bool: ...
def is_number_range(s: str) -> bool: ...
def is_valid_scoreboard_name(name: str) -> bool: ...
