__all__=['is_prime','is_palindrome','is_leap_year','is_even','is_odd']
def is_prime(number:int)->bool:...
def is_palindrome(string:str)->bool:...
def is_leap_year(year:int)->bool:...
def is_even(number:int)->bool:...
def is_odd(number:int)->bool:...