from pydub import AudioSegment
from simpleaudio import PlayObject
__all__=['AudioPlayer','save_text_to_speech']
class AudioPlayer:
	audio:AudioSegment;samples:bytes;sample_rate:int;num_channels:int;bytes_per_sample:int;current_position:int;play_obj:PlayObject|None;is_playing:bool|None
	def __init__(self,file_path:str)->None:...
	def play(self)->None:...
	def pause(self)->None:...
	def resume(self)->None:...
	def stop(self)->None:...
	def get_position(self)->int:...
	def set_position(self,position:int)->None:...
def save_text_to_speech(text:str,name:str,dir:str,language:str='en')->None:...