from _typeshed import Incomplete
__all__=['AudioPlayer','save_text_to_speech']
class AudioPlayer:
	audio:Incomplete;samples:Incomplete;sample_rate:Incomplete;num_channels:Incomplete;bytes_per_sample:Incomplete;current_position:int;play_obj:Incomplete;is_playing:bool
	def __init__(self,file_path:str)->None:...
	def play(self)->None:...
	def pause(self)->None:...
	def resume(self)->None:...
	def stop(self)->None:...
	def get_position(self)->int:...
	def set_position(self,position:int)->None:...
def save_text_to_speech(text:str,name:str,dir:str,language:str='en')->None:...