__all__=['format_seconds','format_minutes','format_hours','format_days','format_weeks','format_years','unformat_time']
def format_seconds(duration:int)->str:...
def format_minutes(duration:int)->str:...
def format_hours(duration:int)->str:...
def format_days(duration:int)->str:...
def format_weeks(duration:int)->str:...
def format_years(duration:int)->str:...
def unformat_time(formatted_time:str)->int:...