__all__ = ['is_url', 'remove_html_tags', 'is_internet_connected', 'is_url_available', 'download_youtube_video', 'download_youtube_playlist', 'get_youtube_playlist_info', 'get_youtube_video_info', 'get_youtube_video_id', 'get_youtube_video_url', 'get_all_videos_from_youtube_playlist']

def is_url(url: str) -> bool: ...
def remove_html_tags(string: str) -> str: ...
def get_youtube_video_id(input_string: str) -> str: ...
def is_internet_connected(max_timeout: int = 5, website: str = 'https://www.google.com') -> bool: ...
def is_url_available(url: str, check_url: bool = True) -> bool | None: ...
def get_all_videos_from_youtube_playlist(playlist_url: str) -> list[str] | Exception: ...

# Names in __all__ with no definition:
#   download_youtube_playlist
#   download_youtube_video
#   get_youtube_playlist_info
#   get_youtube_video_info
#   get_youtube_video_url
