__all__=['is_url','remove_html_tags','is_internet_connected','is_url_available','get_youtube_video_id','get_all_videos_from_youtube_playlist']
def is_url(url:str)->bool:...
def remove_html_tags(string:str)->str:...
def get_youtube_video_id(input_string:str)->str:...
def is_internet_connected(max_timeout:int=5,website:str='https://www.google.com')->bool:...
def is_url_available(url:str,check_url:bool=True)->bool|None:...
def get_all_videos_from_youtube_playlist(playlist_url:str)->list[str]|Exception:...