from .tbe import get_current_pip_path as get_current_pip_path
from _typeshed import Incomplete
from collections.abc import Iterable
from typing import NoReturn

___all__: Incomplete
PIP_c: Incomplete
found: bool

def is_library_installed(library_name: str) -> bool: ...
def download_library(library_name: str) -> tuple[bool, str]: ...
def get_installed_python_versions() -> list[str]: ...
def install_library_from_github(github_repo_url: str) -> None: ...
def install_all_libraries(libs: Iterable[str]) -> list[tuple[bool, str]]: ...
def install_missing_tge_libraries() -> NoReturn | None: ...
