from typing import NoReturn
__all__=['install_library','is_library_installed','install_missing_tge_libraries']
def is_library_installed(library_name:str)->bool:...
def install_library(library_name:str,pip_path:str|None=...,tried_commands:list[list[str]]|None=None)->tuple[bool,str]:...
def install_missing_tge_libraries()->NoReturn|None:...