__all__=['generate_password','random_bool','generate_random_hex_color','generate_random_color','generate_random_hex_color']
def generate_password(length:int)->str:...
def random_bool()->bool:...
def generate_random_hex_color()->str:...
def generate_random_color()->tuple[int,int,int]:...