class Timer:
	start_time:int|float;offset:int|float
	def __init__(self,start_time:int|float,offset:int|float=0)->None:...
	def add_time(self,amount:int|float)->float:...
	def subtract_time(self,amount:int|float)->float:...
	def get_timer_start_time(self)->float:...
	def get_timer_offset(self)->float:...
	def set_start_time(self,value:int|float)->None:...
	def set_offset(self,value:int|float)->None:...
	def get_time(self)->float:...
class TimerManager:
	timers:dict[str,Timer]
	def __init__(self)->None:...
	def start_timer(self,timer_name:str)->None:...
	def stop_timer(self,timer_name:str)->int|float:...
	def get_timer(self,timer_name:str)->int|float:...
	def does_timer_exist(self,timer_name:str)->bool:...
	def get_all_timers(self)->list[str]:...
	def add_time_to_timer(self,timer_name:str,amount:int|float)->float:...
	def remove_time_from_timer(self,timer_name:str,amount:int|float)->float:...
def get_date()->tuple[int,int,int,int,int,int,int]:...
def get_timezone_offset()->int:...
def unix_converter(time:int)->str:...