__all__ = ['copy_to_clipboard', 'get_clipboard', 'clear_clipboard']

def copy_to_clipboard(text: str, user32: None = None, kernel32: None = None) -> None: ...
def get_clipboard(user32: None = None, kernel32: None = None) -> str: ...
def clear_clipboard(user32: None = None) -> None: ...
