from ..shared import ctypes

__all__ = ['copy_to_clipboard', 'get_clipboard', 'clear_clipboard']

def get_clipboard(user32: ctypes.WinDLL = ..., kernel32: ctypes.WinDLL = ...) -> str: ...
def copy_to_clipboard(text: str, user32: ctypes.WinDLL = ..., kernel32: ctypes.WinDLL = ...): ...
def clear_clipboard(user32: ctypes.WinDLL = ...) -> None: ...
