from _typeshed import Incomplete
from unittest import TestCase

class TestBigintAsString(TestCase):
    values: Incomplete
    options: Incomplete
    def test_ints(self) -> None: ...
    def test_lists(self) -> None: ...
    def test_dicts(self) -> None: ...
    def test_dict_keys(self) -> None: ...
