import hjson as json
from unittest import TestCase

class JSONTestObject: ...

class RecursiveJSONEncoder(json.JSONEncoder):
    recurse: bool
    def default(self, o): ...

class TestRecursion(TestCase):
    def test_listrecursion(self) -> None: ...
    def test_dictrecursion(self) -> None: ...
    def test_defaultrecursion(self) -> None: ...
