import unittest
from _typeshed import Incomplete

class TestTool(unittest.TestCase):
    data: str
    expect: Incomplete
    def runTool(self, args: Incomplete | None = None, data: Incomplete | None = None): ...
    def test_stdin_stdout(self) -> None: ...
    def test_infile_stdout(self) -> None: ...
    def x_test_infile_outfile(self) -> None: ...
