from hjson.compat import long_type as long_type, text_type as text_type
from hjson.decoder import NaN as NaN, NegInf as NegInf, PosInf as PosInf
from unittest import TestCase

class TestFloat(TestCase):
    def test_degenerates_ignore(self) -> None: ...
    def test_floats(self) -> None: ...
    def test_ints(self) -> None: ...
