from unittest import TestCase

def default_iterable(obj): ...

class TestCheckCircular(TestCase):
    def test_circular_dict(self) -> None: ...
    def test_circular_list(self) -> None: ...
    def test_circular_composite(self) -> None: ...
    def test_circular_default(self) -> None: ...
    def test_circular_off_default(self) -> None: ...
