from hjson import OrderedDict as OrderedDict
from hjson.compat import StringIO as StringIO
from unittest import TestCase

class TestDecode(TestCase):
    def assertIs(self, a, b) -> None: ...
    def test_decimal(self) -> None: ...
    def test_float(self) -> None: ...
    def test_decoder_optimizations(self) -> None: ...
    def test_empty_objects(self) -> None: ...
    def test_object_pairs_hook(self): ...
    def check_keys_reuse(self, source, loads) -> None: ...
    def test_keys_reuse_str(self) -> None: ...
    def test_keys_reuse_unicode(self) -> None: ...
    def test_empty_strings(self) -> None: ...
    def test_multiline_string(self) -> None: ...
    def test_raw_decode(self) -> None: ...
    def test_bounds_checking(self) -> None: ...
