from _typeshed import Incomplete
from unittest import TestCase

class TestBitSizeIntAsString(TestCase):
    values: Incomplete
    def test_invalid_counts(self) -> None: ...
    def test_ints_outside_range_fails(self) -> None: ...
    def test_ints(self) -> None: ...
    def test_lists(self) -> None: ...
    def test_dicts(self) -> None: ...
    def test_dict_keys(self) -> None: ...
