from hjson.compat import b as b, u as u
from unittest import TestCase

class TestErrors(TestCase):
    def test_string_keys_error(self) -> None: ...
    def test_decode_error(self) -> None: ...
    def test_scan_error(self) -> None: ...
    def test_error_is_pickable(self) -> None: ...
