from _typeshed import Incomplete
from unittest import TestCase

class TestAssets(TestCase):
    assetsDir: Incomplete
    assets: Incomplete
    maxDiff: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def load(self, name, cr): ...
    def check(self, name, file, inputCr) -> None: ...
    def test_files(self) -> None: ...
