from hjson.compat import StringIO as StringIO
from unittest import TestCase

class TestIndent(TestCase):
    def test_indent(self) -> None: ...
    def test_indent0(self) -> None: ...
    def test_separators(self) -> None: ...
