from _typeshed import Incomplete
from functools import cached_property as cached_property
from typing import NamedTuple
def system():...
def java_ver(release:str='',vendor:str='',vminfo=('','',''),osinfo=('','','')):...
def win32_ver(release:str='',version:str='',csd:str='',ptype:str=''):...
def uname():...
class uname_result(NamedTuple('uname_result_base',[('system',Incomplete),('node',Incomplete),('release',Incomplete),('version',Incomplete),('machine',Incomplete)])):
	@cached_property
	def processor(self):...
	def __iter__(self):...
	def __getitem__(self,key):...
	def __len__(self)->int:...
	def __reduce__(self):...
class _Processor:
	@classmethod
	def get(cls):...
	def from_subprocess():...