from typing import Any

class YouTube:
    def __init__(self, url: str) -> None: ...

    def streams(self) -> 'StreamQuery': ...

    def download(self, *args: Any, **kwargs: Any) -> None: ...


class StreamQuery:
    def filter(self, **kwargs: Any) -> 'StreamQuery': ...

    def first(self) -> 'Stream': ...


class Stream:
    def download(self, *args: Any, **kwargs: Any) -> None: ...


class Playlist:
    def __init__(self, url: str) -> None: ...

    def videos(self) -> list[YouTube]: ...

    def title(self) -> str: ...
    @property
    def video_urls(self) -> list[str]: ...