__all__ = ['is_key_pressed', 'press_key', 'hold_key', 'release_key', 'key_to_virtual_key']

def is_key_pressed(key_code: int) -> bool: ...
def press_key(key_code: int) -> None: ...
def hold_key(key_code: int) -> None: ...
def release_key(key_code: int) -> None: ...
def key_to_virtual_key(key: str) -> int | None: ...
