from tkinter import messagebox
def show_message(message_level,user_feedback_level=0,title=None,message=None,**F):
	'\n    Display a message box to the user with customizable parameters.\n\n    This function provides a convenient way to display different types of message boxes\n    with varying levels of user feedback options. It uses the `messagebox` module from\n    the `tkinter` library to create the message box dialog.\n\n    Parameters:\n    message_level (int): The level of the message box. Should be an integer between 0 and 3.\n                        0: Information message\n                        1: Warning message\n                        2: Error message\n                        3: Question message\n\n    user_feedback_level (int, optional): The level of user feedback options. Should be\n                                        an integer between 0 and 5. Defaults to 0.\n                                        0: OK button\n                                        1: OK and Cancel buttons\n                                        2: Yes and No buttons (returns True for \'yes\' and False for \'no\')\n                                        3: Yes, No, and Cancel buttons\n                                        4: Retry and Cancel buttons\n                                        5: Abort, Retry, and Ignore buttons\n\n    title (str, optional): The title of the message box. Defaults to None.\n\n    message (str, optional): The message content to be displayed in the message box.\n                            Defaults to None.\n\n    **options: Additional options that can be passed to the `messagebox` module for\n            further customization of the message box appearance.\n\n    Returns:\n    - For user_feedback_level 2 (Yes/No): True if \'yes\' is clicked, False if \'no\' is clicked.\n    - For other user_feedback_levels: The button text that was clicked (\'ok\', \'cancel\', etc.).\n\n    Example usage:\n    ```\n    result = show_message(1, 2, "Warning", "Are you sure you want to proceed?")\n    if result:\n        print("User confirmed.")\n    else:\n        print("User declined.")\n    ```\n\n    Note:\n    - If the provided `message_level` or `user_feedback_level` values are out of range,\n    they will be adjusted to the nearest valid value.\n    - The actual appearance of the message box may vary depending on the platform\'s\n    native dialog styles.\n    ';B=message_level;A=user_feedback_level;C=['info','warning','error','question'];D=['ok','okcancel','yesno','yesnocancel','retrycancel','abortretryignore']
	if B<0 or B>len(C):B=0
	if A<0 or A>len(D):A=0
	E=messagebox._show(title,message,C[B],D[A],**F)
	if A==2:
		if E=='yes':return True
		else:return False
	else:return E
if __name__=='__main__':print(show_message(message_level=2,user_feedback_level=0,title='Error!',message='An Error occurred.'))