def format_number(number):'\n    Formats an integer number with commas as thousands separators.\n\n    Args:\n        number (int): An integer that needs to be formatted.\n\n    Returns:\n        str: A string representation of the formatted number with commas as thousands separators.\n    ';return'{:,}'.format(number)
def format_seconds(duration):'\n    Formats a duration given in seconds into a string representation.\n\n    Args:\n        duration (int): The duration in seconds.\n\n    Returns:\n        str: The formatted duration string in the format "Xh Ym Zs".\n\n    Example:\n        >>> format_seconds(3665)\n        \'1h 1m 5s\'\n    ';A=duration;B=A//3600;C=A%3600//60;D=A%60;E=f"{B}h {C}m {D}s";return E
def format_minutes(duration):'\n    Formats a duration given in minutes into a string representation.\n\n    Args:\n        duration (int): The duration in minutes.\n\n    Returns:\n        str: The formatted duration string in the format "Xh Ym Zs".\n\n    Example:\n        >>> format_minutes(125)\n        \'2h 5m 0s\'\n    ';A=duration;B=A//60//60;C=A//60%60;D=A%60;E=f"{B}h {C}m {D}s";return E
def format_hours(duration):'\n    Formats a duration given in hours into a string representation.\n\n    Args:\n        duration (int): The duration in hours.\n\n    Returns:\n        str: The formatted duration string in the format "Xh Ym Zs".\n\n    Example:\n        >>> format_hours(2)\n        \'2h 0m 0s\'\n    ';A=duration;B=A//3600;C=A%3600//60;D=A%60;E=f"{B}h {C}m {D}s";return E
def format_days(duration):'\n    Formats a duration given in days into a string representation.\n\n    Args:\n        duration (int): The duration in days.\n\n    Returns:\n        str: The formatted duration string in the format "Xh Ym Zs".\n\n    Example:\n        >>> format_days(3)\n        \'72h 0m 0s\'\n    ';A=duration;B=A//3600;C=A%3600//60;D=A%60;E=f"{B}h {C}m {D}s";return E
def format_weeks(duration):'\n    Formats a duration given in weeks into a string representation.\n\n    Args:\n        duration (int): The duration in weeks.\n\n    Returns:\n        str: The formatted duration string in the format "Xh Ym Zs".\n\n    Example:\n        >>> format_weeks(2)\n        \'336h 0m 0s\'\n    ';A=duration;B=A//3600;C=A%3600//60;D=A%60;E=f"{B}h {C}m {D}s";return E
def format_years(duration):'\n    Formats a duration given in years into a string representation.\n\n    Args:\n        duration (int): The duration in years.\n\n    Returns:\n        str: The formatted duration string in the format "Xh Ym Zs".\n\n    Example:\n        >>> format_years(1)\n        \'8760h 0m 0s\'\n    ';A=duration;B=A//3600;C=A%3600//60;D=A%60;E=f"{B}h {C}m {D}s";return E
def unformat_time(formatted_time):
	'\n    Converts a formatted time string into its equivalent duration in seconds.\n\n    Args:\n        formatted_time (str): The formatted time string in the format "Xh Ym Zs".\n\n    Returns:\n        int: The duration in seconds.\n\n    Example:\n        >>> unformat_time(\'2h 30m 45s\')\n        9045\n    ';A=formatted_time
	try:B=int(A.split('h')[0].strip());C=int(A.split('m')[0].strip());D=int(A.split('s')[0].strip());return B*3600+C*60+D
	except:return 0