from _typeshed import Incomplete

__all__ = ['copy', 'paste', 'set_clipboard', 'determine_clipboard']

class PyperclipException(RuntimeError): ...

class PyperclipWindowsException(PyperclipException):
    def __init__(self, message) -> None: ...

class PyperclipTimeoutException(PyperclipException): ...

class CheckedCall:
    def __init__(self, f) -> None: ...
    def __call__(self, *args): ...
    def __setattr__(self, key, value) -> None: ...

def determine_clipboard(): ...
def set_clipboard(clipboard) -> None: ...

copy: Incomplete
paste: Incomplete
