from typing import List

class YoutubeDL:
    def __init__(self, options: dict = None) -> None: ...

    def download(self, urls: list[str]) -> None: ...

    # Context manager methods
    def __enter__(self) -> 'YoutubeDL': ...
    
    def __exit__(self, exc_type: type, exc_val: Exception, exc_tb: Any) -> None: ...

# Exception for connection issues
class ConnectionError(Exception):
    pass  # or define any specific attributes if needed

# Add Playlist class
class Playlist:
    def __init__(self, url: str) -> None: ...

    def videos(self) -> list[YouTube]: ...
    @property
    def video_urls(self) -> list[str]: ...