import pygame
from typing import Callable, NoReturn

__all__ = ['update_screen', 'render_text', 'load_images_from_directory', 'handle_events', 'check_collision', 'check_collision_with_all', 'pygame_exit', 'background_color', 'draw_texture_at', 'exit']

def update_screen(clock: pygame.time.Clock, fps: int = 0) -> None: ...
def render_text(screen: pygame.Surface, text: str, font_name: str, size: int, color: tuple[int, int, int], position: tuple[int, int]) -> None: ...
def load_images_from_directory(directory_path: str) -> int: ...
def handle_events(quit_callback: Callable[..., NoReturn] = ..., key_callback: Callable[..., None] = ..., mouse_button_callback: Callable[..., None] = ..., misc_callback: Callable[..., None] = ...) -> None: ...
def check_collision(*rects: pygame.Rect) -> bool: ...
def check_collision_with_all(*rects: pygame.Rect) -> bool: ...
def pygame_exit() -> None: ...
def background_color(window: pygame.Surface, color: tuple[int, int, int]) -> None: ...
def draw_texture_at(surface: pygame.Surface, texture: pygame.Surface, position: tuple[int, int]) -> None: ...
def exit() -> NoReturn: ...
