from .clipboard.clipboard_pyperclip import clear_clipboard as clear_clipboard, copy_to_clipboard as copy_to_clipboard, get_clipboard as get_clipboard

__all__ = ['save_clipboard_to_file', 'load_clipboard_from_file', 'append_to_clipboard', 'prepend_to_clipboard', 'get_clipboard_size', 'get_clipboard_file_extension', 'write_out_clipboard', 'clear_clipboard', 'get_clipboard', 'copy_to_clipboard']

def save_clipboard_to_file(file_path: str) -> bool: ...
def load_clipboard_from_file(file_path: str) -> bool: ...
def append_to_clipboard(text: str) -> None: ...
def prepend_to_clipboard(text: str) -> None: ...
def get_clipboard_size() -> int: ...
def get_clipboard_file_extension() -> str: ...
def write_out_clipboard() -> None: ...
