from.shared import*
from.cursor.cursor_operations_pynput import get_mouse_position as get_mouse_position,is_left_button_pressed as is_left_button_pressed,is_middle_button_pressed as is_middle_button_pressed,is_right_button_pressed as is_right_button_pressed,left_click as left_click,left_mouse_up as left_mouse_up,middle_click as middle_click,middle_mouse_down as middle_mouse_down,middle_mouse_up as middle_mouse_up,right_click as right_click,right_mouse_up as right_mouse_up,scroll as scroll,scroll_horizontal as scroll_horizontal,scroll_vertical as scroll_vertical,set_mouse_to as set_mouse_to
__all__=['click_mouse_button','hold_mouse_button','release_mouse_button','click_mouse_button_at','left_click_at','double_left_click','double_left_click_at','right_click_at','double_right_click','MiddleClick_at','drag_to','drag_obj_to','left_click','right_click','middle_click','set_mouse_to','get_mouse_position','is_right_button_pressed','is_middle_button_pressed','is_left_button_pressed','middle_mouse_up','right_mouse_up','middle_mouse_down','left_mouse_up','scroll','scroll_horizontal','scroll_vertical']
def click_mouse_button(button_number:int)->None:...
def hold_mouse_button(button_number:int)->None:...
def release_mouse_button(button_number:int)->None:...
def click_mouse_button_at(button_number:int,x:int,y:int)->None:...
def left_click_at(x:int,y:int)->None:...
def double_left_click()->None:...
def double_left_click_at(x:int,y:int)->None:...
def right_click_at(x:int,y:int)->None:...
def double_right_click()->None:...
def MiddleClick_at(x:int,y:int)->None:...
def drag_to(x:int,y:int):...
def drag_obj_to(x:int,y:int,a:int,b:int):...