from _typeshed import Incomplete
from typing import Protocol
__all__=['is_key_pressed','press_key','hold_key','release_key','key_to_virtual_key','keys']
class KeyboardModule(Protocol):
	def is_key_pressed(self,key:str)->bool:...
	def press_key(self,key:str)->None:...
	def hold_key(self,key:str)->None:...
	def release_key(self,key:str)->None:...
	def key_to_virtual_key(self,key:str)->int:...
	keys:dict[str,int]
is_key_pressed:Incomplete
press_key:Incomplete
hold_key:Incomplete
release_key:Incomplete
key_to_virtual_key:Incomplete
keys:Incomplete