from ..shared import ctypes

__all__ = ['left_click', 'right_click', 'middle_click', 'set_mouse_to', 'get_mouse_position', 'is_right_button_pressed', 'is_middle_button_pressed', 'is_left_button_pressed', 'middle_mouse_up', 'right_mouse_up', 'middle_mouse_down', 'left_mouse_up', 'scroll', 'scroll_horizontal', 'scroll_vertical', 'left_mouse_down', 'right_mouse_down', 'middle_mouse_down']

class POINT(ctypes.Structure): ...

def set_mouse_to(coords: tuple[int, int], screen_width: int = ..., screen_height: int = ...) -> None: ...
def get_mouse_position() -> tuple[int, int]: ...
def left_click() -> None: ...
def right_click() -> None: ...
def middle_click() -> None: ...
def scroll_vertical(clicks: int, wheel_delta: int = ...) -> None: ...
def scroll_horizontal(clicks: int, wheel_delta: int = ...) -> None: ...
def scroll(dx: int | None = None, dy: int | None = None, wheel_delta_x: int = ..., wheel_delta_y: int = ...) -> None: ...
def left_mouse_down() -> None: ...
def right_mouse_down() -> None: ...
def middle_mouse_down() -> None: ...
def left_mouse_up() -> None: ...
def right_mouse_up() -> None: ...
def middle_mouse_up() -> None: ...
def is_left_button_pressed(): ...
def is_middle_button_pressed(): ...
def is_right_button_pressed(): ...
