__all__=['convert_binary_to_decimal','convert_decimal_to_binary','convert_decimal_to_hexadecimal','convert_hexadecimal_to_decimal','convert_bytes','convert_byte_to_kilobyte','convert_kilobyte_to_megabyte','convert_megabyte_to_gigabyte']
def convert_binary_to_decimal(binary:str)->int:...
def convert_decimal_to_binary(decimal:int)->str:...
def convert_decimal_to_hexadecimal(decimal:int)->str:...
def convert_hexadecimal_to_decimal(hexadecimal:str)->int:...
def convert_bytes(value:int,from_unit:str,to_unit:str)->int:...
def convert_byte_to_kilobyte(bytes:int)->int:...
def convert_kilobyte_to_megabyte(kilobytes:int)->int:...
def convert_megabyte_to_gigabyte(megabytes:int)->int:...