__all__=['celsius_to_fahrenheit','fahrenheit_to_celsius','celsius_to_kelvin','kelvin_to_celsius','kelvin_to_fahrenheit','fahrenheit_to_kelvin']
def celsius_to_fahrenheit(celsius:int|float)->float:...
def fahrenheit_to_celsius(fahrenheit:int|float)->float:...
def celsius_to_kelvin(celsius:int|float)->float:...
def kelvin_to_celsius(kelvin:int|float)->float:...
def kelvin_to_fahrenheit(kelvin:int|float)->float:...
def fahrenheit_to_kelvin(fahrenheit:int|float)->float:...