__all__=['calculate_present_value','percentage_increase','percentage_decrease','discount_price','body_mass_index']
def calculate_present_value(principal:int|float,rate:int|float,years:int)->float:...
def percentage_increase(number:int|float,percentage:int|float)->float:...
def percentage_decrease(old_grade:int|float,new_grade:int|float)->float:...
def discount_price(price:int|float,discount:int|float)->float:...
def body_mass_index(weight:int|float,height:int|float)->float:...