import numpy as np

__all__ = ['average_grade', 'median_grade', 'mode_grade', 'standard_deviation', 'median', 'median_absolute_deviation', 'correlation', 'calculate_entropy', 'median_absolute_error']

def average_grade(grades: list[int | float]) -> float: ...
def median_grade(grades: list[int | float]) -> float: ...
def mode_grade(grades: list[int | float]) -> float: ...
def standard_deviation(grades: list[int | float]) -> float: ...
def median(grades: list[int | float]) -> float: ...
def median_absolute_deviation(data: list[int | float]) -> float: ...
def correlation(data1: float, data2: float) -> np.ndarray: ...
def calculate_entropy(grades: list[int | float]) -> float: ...
def median_absolute_error(grades: list[int | float]) -> float: ...
