def is_window_minimized(window_id:int|str|None)->bool:...
def minimize_window(window_id:int|str|None):...
def get_window_position(window_id:int|None)->tuple[int,int,int,int]|None:...
def maximize_window(window_id:int|str|None):...
def set_window_position(window_id:int|str|None,x:int,y:int,width:int,height:int):...
def get_window_by_title(title:str)->str|None:...
def is_xdotool_installed():...
def install_xdotool():...