from AppKit import NSApplication as NSApplication, NSWindow as NSWindow, NSWorkspace as NSWorkspace

def is_window_minimized(window: NSWindow): ...
def minimize_window(window: NSWindow): ...
def get_window_position(window: NSWindow) -> tuple[int, int, int, int] | None: ...
def maximize_window(window: NSWindow): ...
def set_window_position(window: NSWindow, x: int, y: int, width: int, height: int): ...
def get_window_by_title(title: str) -> NSWindow | None: ...
